# 项目信息
site_name: 风格指南 # 项目名称
# 配置
theme:
  name: material # 主题名称，Material已经是最优秀的选择了，相信我。
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
        primary: blue
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    features:
      - search.highlight # 搜索高亮
      - search.suggest # 搜索建议
# 扩展
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
# 自定义样式
extra_css:
  - resources/extra.css
nav:
    - 文件规范: 'file.md'
    - 图片规范:
      - 'icon.md'
      - 'typology.md'
      - 'screenshot.md'
    - 标点规范:
      - 'space.md'
