name: Publish docs via GitHub Pages
on:
   push:
       branches:
         - master # 指定触发部署的分支，通常是main或master
jobs:
    build:
      name: Deploy docs
      runs-on: ubuntu-latest  # 使用最新的Ubuntu虚拟环境
      steps:
      # 官方action, 将代码拉取到虚拟机
        - name: Checkout master
          uses: actions/checkout@v2
      # 将MkDocs的文档生成并部署到GitHub Pages中
        - name: Deploy docs
          uses: mhausenblas/mkdocs-deploy-gh-pages@master
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             EXTRA_PACKAGES: build-base